#!/bin/bash

cpuPercent=`grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print int(usage)}'`

if [ $cpuPercent -gt 90 ]; then
  echo "Critical: Average CPU is at $cpuPercent%"
  exit 2
elif [ $cpuPercent -gt 80 ]; then
  echo "Warning: Average CPU is at $cpuPercent%"
  exit 1
fi

echo "Average CPU is at $cpuPercent%"
exit 0
