#!/bin/bash

dfOutput=`df -k | grep -v Filesystem`
exitVal=0

while read -r line; do
  percent=`echo $line | awk '{print $5}' | awk -F\% '{print $1}'`

  if [ $percent -gt 90 ]; then
    echo "$line"
    exitVal=2
  elif [ $percent -gt 80 ]; then
    echo "$line"
    if [ $exitVal -ne 2 ]; then
      exitVal=1
    fi
  fi
done <<< "$dfOutput"

if [ $exitVal -eq 0 ]; then
  echo "All drives are within acceptable limits."
fi

exit $exitVal
